
const data = {
	products: [
		{
			name: 'Dark Project Keycaps',
			slug: 'dark-project-keycaps-1',
			image: 'dpkeycaps.png',
			category: 'keycaps',
			price: 1600.00,
			countInStock: 12,
			brand: 'Dark Project',
			rating: 4.5,
			numReviews: 8,
			description: 'Introducing the Dark Project keycap set - the perfect way to take your keyboard setup to the next level. With a sleek and modern design, these keycaps are sure to impress even the most discerning of gamers and typists.',
		},
		{
			name: 'GMK Keycaps',
			slug: 'gmk-keycaps-2',
			category: 'keycaps',
			image: 'gmkkeycaps.png',
			price: 1800.00,
			countInStock: 6,
			brand: 'GMK',
			rating: 4.8,
			numReviews: 5,
			description: 'Introducing the GMK keycap set - the pinnacle of high-quality keycaps. Made in Germany using a process called double-shot molding, these keycaps are crafted with unparalleled precision and attention to detail.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
		{
			name: 'Cherry MX RED Switches',
			slug: 'cherry-mx-red-switches',
			category: 'keycaps',
			image: 'chmxred.png',
			price: 4000.00,
			countInStock: 12,
			brand: 'Cherry MX',
			rating: 4.9,
			numReviews: 26,
			description: 'Introducing the Cherry MX Red switches - the perfect choice for gamers and typists who demand a smooth and responsive typing experience. Known for their quiet operation and linear feel, these switches are designed to provide optimal performance and accuracy with every keystroke.',
		},
	],
};

export default data;
